FunD-StockProject/StockProject-Backend

Dockerfile
Jenkinsfile
build.gradle
src/main/java/com/fund/stockProject/global/config/JasyptConfig.java
src/main/resources/application.yml

CHORE(#4): jasypt 암호화 설정

---

build.gradle
src/main/java/com/fund/stockProject/global/config/SwaggerConfig.java
src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/entity/Stock.java

- close #4
- Swagger 설정
- 아키텍처 기본 설정

CHORE(#4): swagger 설정 및 아키텍처 기본 설정

---

Jenkinsfile

CHORE(#4): jenkinsfile 설정 변경

---

build.gradle
src/main/java/com/fund/stockProject/StockProjectApplication.java
src/main/java/com/fund/stockProject/global/entity/Core.java
src/main/java/com/fund/stockProject/stock/entity/Score.java
src/main/java/com/fund/stockProject/stock/entity/Stock.java
src/main/resources/application.yml

- close #3
- DB 세팅
- 엔티티 정의
- jasypt적용

FEAT(#3): stock, score db및 관련 코드 설정

---

src/main/java/com/fund/stockProject/stock/entity/Score.java

CHORE(#4): Score 엔티티 변경

---

build.gradle
src/main/java/com/fund/stockProject/global/config/QueryDslConfig.java
src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/dto/response/StockSearchResponse.java
src/main/java/com/fund/stockProject/stock/repository/StockQueryRepository.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #3 
- 검색어 자동완성 API 
- 주식 종목 검색 API
- QueryDSL 설정

Stock feat search

---

src/main/java/com/fund/stockProject/score/controller/ScoreController.java
src/main/java/com/fund/stockProject/score/dto/response/ScoreResponse.java
src/main/java/com/fund/stockProject/score/entity/Score.java
src/main/java/com/fund/stockProject/score/repository/ScoreRepository.java
src/main/java/com/fund/stockProject/score/service/ScoreService.java
src/main/java/com/fund/stockProject/stock/entity/Stock.java

FEAT(#5): Score 조회 api 개발

---

build.gradle
src/main/java/com/fund/stockProject/global/config/SchedulerConfig.java
src/main/java/com/fund/stockProject/global/config/SecurityHttpConfig.java
src/main/java/com/fund/stockProject/global/dto/request/AccessTokenRequest.java
src/main/java/com/fund/stockProject/global/dto/response/AccessTokenResponse.java
src/main/java/com/fund/stockProject/global/scheduler/AccessTokenScheduler.java
src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/domain/COUNTRY.java
src/main/java/com/fund/stockProject/stock/dto/response/StockKoreaVolumeRankResponse.java
src/main/java/com/fund/stockProject/stock/dto/response/StockOverseaVolumeRankResponse.java
src/main/java/com/fund/stockProject/stock/dto/response/StockSimpleResponse.java
src/main/java/com/fund/stockProject/stock/repository/StockRepository.java
src/main/java/com/fund/stockProject/stock/service/SecurityService.java
src/main/java/com/fund/stockProject/stock/service/StockService.java
src/main/resources/application.yml

- #12 
- 증권사api연동 및 토큰 세팅, hot api 개발

FEAT(#12): 증권사api연동 및 토큰 세팅, hot api 개발

---

src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/repository/StockRepository.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

FEAT(#12): 떡상/떡락 api 임시 구헌

---

src/main/java/com/fund/stockProject/score/entity/Score.java
src/main/java/com/fund/stockProject/score/repository/ScoreRepository.java
src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/dto/response/StockDiffResponse.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

FEAT(#12): 떡상, 떡락 api 구현

---

src/main/java/com/fund/stockProject/global/config/SecurityHttpConfig.java

FIX(#12): 헤더 세팅 수정

---

src/main/java/com/fund/stockProject/global/config/WebConfig.java

Score feat ai

---

build.gradle
src/main/java/com/fund/stockProject/global/entity/Core.java
src/main/java/com/fund/stockProject/score/entity/Score.java
src/main/java/com/fund/stockProject/score/entity/ScoreId.java
src/main/java/com/fund/stockProject/score/repository/ScoreRepository.java
src/main/java/com/fund/stockProject/score/service/ScoreService.java

- #12
- AI 코드 작성
- 프롬포트 연결
- api 구현
- 엔티티수정

FEAT(#12): AI 점수 api 구현

---

src/main/java/com/fund/stockProject/score/service/ScoreService.java

- #12
- 오늘 데이터 없으면, 전일 데이터 가져오도록 수정

FIX(#12): 오늘 데이터 없으면, 전일 데이터 가져오도록 수정

---

src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/repository/StockQueryRepository.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #24 
- 거래소, 점수를 기준으로 관련 종목 조회

FEAT(#24) 관련 종목 조회 API 개발

---

src/main/java/com/fund/stockProject/global/scheduler/ScoreUpdateScheduler.java
src/main/java/com/fund/stockProject/score/repository/ScoreRepository.java
src/main/java/com/fund/stockProject/score/service/ScoreService.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

FEAT(#12): AI update 배치 개발

---

src/main/java/com/fund/stockProject/stock/repository/StockQueryRepository.java

- close #3 
- 검색어 자동완성 개수 변경(-> 30개)

REFACTOR(#3): 검색어 자동완성 개수 변경

---

Dockerfile
Jenkinsfile
src/main/java/com/fund/stockProject/score/controller/ScoreController.java
src/main/java/com/fund/stockProject/score/service/ScoreService.java
src/main/java/com/fund/stockProject/stock/dto/response/StockWordResponse.java

- close #28 
- 워드클라우드 api 개발
- 스크립트 작성
- Dockerfile 등 세팅

FEAT(#28): 워드클라우드 api 개발

---

src/main/java/com/fund/stockProject/stock/repository/StockQueryRepository.java
src/main/java/com/fund/stockProject/stock/repository/StockRepository.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #24 
- 관련 종목 조회 API 로직 수정

REFACTOR(#24): 관련 종목 조회 API 로직 수정

---

src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #3 
- 검색어 자동완성 거래소 번호 매핑 로직 추가

REFACTOR(#3): 검색어 자동완성 거래소 번호 매핑 로직 추가

---

src/main/java/com/fund/stockProject/stock/repository/StockQueryRepository.java

- close #24 
- 관련종목 조회 중복제거 로직 추가

REFACTOR(#24): 관련종목 조회 중복제거 로직 추가

---

src/main/java/com/fund/stockProject/stock/repository/StockQueryRepository.java

- close #24 
- 관련종목 조회 API 해외 관련 종목 반환 로직 수정

REFACTOR(#24): 관련종목 조회 API 해외 관련 종목 반환 로직 수정

---

src/main/java/com/fund/stockProject/stock/repository/StockQueryRepository.java

- close #24 
- 관련 종목 조회 거래소 매핑 조건 추가

REFACTOR(#24): 관련 종목 조회 거래소 매핑 조건 추가

---

src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/domain/EXCHANGENUM.java
src/main/java/com/fund/stockProject/stock/dto/response/StockInfoResponse.java
src/main/java/com/fund/stockProject/stock/service/SecurityService.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #43
- 주식 종목 정보 제공 api 개발

FEAT(#43): 주식 종목 정보 제공 api 개발

---

src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/dto/response/StockChartResponse.java
src/main/java/com/fund/stockProject/stock/entity/Stock.java
src/main/java/com/fund/stockProject/stock/service/SecurityService.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

FEAT(#29): 주식 차트 API 개발

---

src/main/java/com/fund/stockProject/stock/repository/StockRepository.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

REFACTOR(#3): 주식 검색 조건 변경

---

src/main/java/com/fund/stockProject/stock/service/StockService.java

FIX(#45): 떡상, 떡락 api 수정 -> 오늘날짜 데이터 우선 리턴

---

src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/repository/StockRepository.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #3 
- 주식 검색 국가 구분 로직 추가

REFACTOR(#3): 주식 검색 국가 구분 로직 추가

---

src/main/java/com/fund/stockProject/keyword/controller/KeywordController.java
src/main/java/com/fund/stockProject/keyword/entity/Keyword.java
src/main/java/com/fund/stockProject/keyword/entity/StockKeyword.java
src/main/java/com/fund/stockProject/keyword/repository/KeywordRepository.java
src/main/java/com/fund/stockProject/keyword/service/KeywordService.java
src/main/java/com/fund/stockProject/stock/entity/Stock.java

FEAT(#52): 키워드 엔티티 개발 및 설정

---

src/main/java/com/fund/stockProject/global/scheduler/KeywordCleanupScheduler.java
src/main/java/com/fund/stockProject/keyword/dto/KeywordDto.java
src/main/java/com/fund/stockProject/keyword/entity/Keyword.java
src/main/java/com/fund/stockProject/keyword/repository/KeywordRepository.java
src/main/java/com/fund/stockProject/keyword/repository/StockKeywordRepository.java
src/main/java/com/fund/stockProject/score/controller/ScoreController.java
src/main/java/com/fund/stockProject/score/dto/response/ScoreKeywordResponse.java
src/main/java/com/fund/stockProject/score/repository/ScoreRepository.java
src/main/java/com/fund/stockProject/score/service/ScoreService.java

- #52
- 키워드 조회 api 개발
- 키워드 세팅
- 키워드 업데이트 스케줄러 개발 중

Stock chore

---

Dockerfile
Jenkinsfile

FEAT(#52): 키워드 업데이트 스케줄러 Docker, Jenkins 적용

---

Dockerfile
Jenkinsfile
src/main/java/com/fund/stockProject/global/scheduler/ScoreUpdateScheduler.java
src/main/java/com/fund/stockProject/score/controller/ScoreController.java
src/main/java/com/fund/stockProject/score/dto/response/ScoreIndexResponse.java
src/main/java/com/fund/stockProject/score/service/ScoreService.java
src/main/java/com/fund/stockProject/stock/repository/StockRepository.java

- close #56
- 공포지수, 시장지수 api 및 업데이트 스케줄러 개발

FEAT(#56): 공포지수, 시장지수 api 및 업데이트 스케줄러 개발

---

src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/domain/CATEGORY.java
src/main/java/com/fund/stockProject/stock/dto/response/StockCategoryResponse.java
src/main/java/com/fund/stockProject/stock/dto/response/StockKoreaMarketCapResponse.java
src/main/java/com/fund/stockProject/stock/dto/response/StockKoreaRisingDescentResponse.java
src/main/java/com/fund/stockProject/stock/dto/response/StockOverseaRankResponse.java
src/main/java/com/fund/stockProject/stock/service/SecurityService.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #55
- 종목 차트별 인간지표 api 전체 구현

CHORE(#55): 종목 차트별 인간지표 api 전체 구현

---

src/main/java/com/fund/stockProject/keyword/controller/KeywordController.java
src/main/java/com/fund/stockProject/keyword/dto/PopularKeywordResponse.java
src/main/java/com/fund/stockProject/keyword/repository/KeywordRepository.java
src/main/java/com/fund/stockProject/keyword/service/KeywordService.java
src/main/java/com/fund/stockProject/stock/dto/response/StockDiffResponse.java
src/main/java/com/fund/stockProject/stock/dto/response/StockSimpleResponse.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #52 
- 자주 언급되는 키워드 API 개발
- 떡상, 떡락 종목 관련 키워드 반환 로직 추가

주식 키워드 기능 추가 및 관련 api 개발

---

src/main/java/com/fund/stockProject/keyword/controller/KeywordController.java

- close #52 
- 자주 언급되는 키워드 API Controller 변수명 수정

REFACTOR(#52): 자주 언급되는 키워드 API 변수명 수정

---

src/main/java/com/fund/stockProject/global/scheduler/ScoreUpdateScheduler.java
src/main/java/com/fund/stockProject/keyword/entity/StockKeyword.java
src/main/java/com/fund/stockProject/score/service/ScoreService.java

FEAT(#52): 키워드 업데이트 기능 및 스케줄러 개발

---

src/main/java/com/fund/stockProject/keyword/service/KeywordService.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #52 
- 떡상, 떡락 API Keyword 특수기호 및 불용어 필터링 로직 추가
- 자주 언급되는 Keyword API 특수기호 및 불용어 필터링 로직 추가

Keyword 특수기호 및 불용어 필터링 처리

---

src/main/java/com/fund/stockProject/stock/dto/response/StockRelevantResponse.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #52 
- 관련 종목 조회 API 키워드 추가 

REFACTOR(#52): 관련 종목 API 키워드 추가

---

src/main/java/com/fund/stockProject/stock/dto/response/StockRelevantResponse.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #52 
- 관련 종목 API DTO 변수명 오타 수정

REFACTOR(#52): 관련 종목 API DTO 변수명 오타 수정

---

src/main/java/com/fund/stockProject/stock/repository/StockQueryRepository.java

- close #3
- 검색어 자동 완성 API 일부 주식 종목 검색 안되는 문제 해결

FIX(#3): 검색어 자동 완성 API 일부 주식 종목 검색 안되는 문제 해결

---

src/main/java/com/fund/stockProject/keyword/dto/KeywordStockResponse.java
src/main/java/com/fund/stockProject/keyword/service/KeywordService.java

- close #52 
- 인기 키워드 결과값 개수 변경 (9개 -> 10개)
- 키워드 검색 결과값 인기 키워드 목록 추가(2개)

키워드 관련 로직 수정

---

Dockerfile
Jenkinsfile
src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/dto/response/StockHotSearchResponse.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

FEAT(#70): 인기검색어 api 구현

---

src/main/java/com/fund/stockProject/stock/repository/StockRepository.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #3 
- 검색 API Symbol 검색 로직 추가

REFACTOR(#3): 검색 API 검색 로직 수정 -> Symbol 검색 로직 추가

---

src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/repository/StockQueryRepository.java

- close #3
- 검색어 자동완성 API Symbol 검색 로직 추가

REFACTOR(#3) 검색어 자동완성 API Symbol 검색 로직 추가

---

src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/service/SecurityService.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #55 
- 주식 차트 API 검색 종료 날짜 추가 및 반환값 최대 개수 설정

REFACTOR(#55): 주식 차트 API 검색 종료 날짜 추가 및 반환값 최대 개수 설정

---

src/main/java/com/fund/stockProject/stock/service/SecurityService.java

- close #55 
- 주식 차트 API: 한투 API 빈 데이터 반환 케이스 예외 처리

REFACTOR(#3): 주식 차트 API 한투 API 빈 데이터 반환 케이스 예외 처리

---

src/main/java/com/fund/stockProject/keyword/controller/KeywordController.java
src/main/java/com/fund/stockProject/keyword/repository/KeywordRepository.java
src/main/java/com/fund/stockProject/keyword/service/KeywordService.java

- close #52 
- 인기 키워드 TOP10 API 구현

FEAT(#3): 인기 키워드 TOP10 API 구현

---

Dockerfile
Jenkinsfile
src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #77
- 종목 요약 api 및 python 구현

FEAT(#77): 종목 요약 api 구현

---

src/main/java/com/fund/stockProject/stock/dto/response/StockSimpleResponse.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

FEAT(#45): hot 지표 api diff 값 추가

---

build.gradle
src/main/resources/application.yml

- close #80 
- Spring Actuator & Prometheus 설정

CHORE(#80): Spring Actuator & Prometheus 설정

---

build.gradle
src/main/resources/application.yml

- close #80 
- spring actuator & prometheus 설정 변경

CHORE(#80): Spring Actuator & Prometheus 설정 변경

---

build.gradle
src/main/resources/application.yml

- close #80 
- Spring Actuator & Prometheus 설정 수정

CHORE(#80): Spring Actuator & Prometheus 설정 수정

---

src/main/resources/application.yml

- close #80 
- Spring Actuator 설정 변경

CHORE(#80): Spring Actuator 설정 변경

---

src/main/java/com/fund/stockProject/score/service/ScoreService.java

- close #12 
- 인간지표 점수 조회 API 오류 수정

FIX(#12): 인간지표 점수 조회 API 오류 수정

---

src/main/resources/application.yml

- close #80 
- Spring Actuator & Prometheus 설정 변경

REFACTOR(#80): Spring Actuator & Prometheus 설정 변경

---

src/main/resources/application.yml

- close #80 
- Spring Actuator Port 설정 변경

REFACTOR(#80): Spring Actuator Port 설정 변경

---

src/main/java/com/fund/stockProject/global/config/SecurityConfig.java

Reverts FunD-StockProject/StockProject-Backend#96

Revert "FIX(#91): 로그인, 회원가입 실행 중 직접 생성되지 않는 빈 등록"

---

src/main/java/com/fund/stockProject/auth/controller/AuthController.java
src/main/java/com/fund/stockProject/auth/controller/OAuth2Controller.java
src/main/java/com/fund/stockProject/auth/controller/TokenController.java

- close #91 
auth 관련 swagger 내용 작성

DOCS(#91): Swagger 내용 작성

---

src/main/java/com/fund/stockProject/auth/entity/User.java
src/main/resources/application.yml

- close #91
유저 엔티티 ID Long에서 Integer로 변경

REFACTOR(#91): 유저 엔티티 ID Long에서 Integer로 변경

---

src/main/java/com/fund/stockProject/auth/service/AuthService.java
src/main/java/com/fund/stockProject/preference/controller/PreferenceController.java
src/main/java/com/fund/stockProject/preference/domain/PreferenceType.java
src/main/java/com/fund/stockProject/preference/dto/BookmarkInfoResponse.java
src/main/java/com/fund/stockProject/preference/entity/Preference.java
src/main/java/com/fund/stockProject/preference/entity/PreferenceId.java
src/main/java/com/fund/stockProject/preference/repository/PreferenceRepository.java
src/main/java/com/fund/stockProject/preference/service/PreferenceService.java
src/main/java/com/fund/stockProject/security/principle/CustomPrincipal.java

- close #108 
북마크, 다신 보지 않음 API 구현

FEAT(#108):  북마크, 다신 보지 않음 API 개발

---

src/main/java/com/fund/stockProject/stock/controller/StockController.java
src/main/java/com/fund/stockProject/stock/dto/response/StockDetailResponse.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

- close #43
주식 종목 부가 정보 api 개발

FEAT(#43): 주식 종목 부가 정보 api 개발

---

src/main/java/com/fund/stockProject/global/config/CorsConfig.java
src/main/java/com/fund/stockProject/global/config/SecurityConfig.java

FIX: CORS CONFIG

---

src/main/java/com/fund/stockProject/auth/controller/OAuth2Controller.java
src/main/java/com/fund/stockProject/auth/dto/NaverTokenResponse.java
src/main/java/com/fund/stockProject/auth/entity/User.java
src/main/java/com/fund/stockProject/auth/service/NaverService.java
src/main/java/com/fund/stockProject/auth/service/OAuth2Service.java
src/main/java/com/fund/stockProject/global/config/SecurityConfig.java
src/main/resources/application.yml

- close #91 
네이버 소셜 로그인/회원가입 연동 기능 구현

 FEAT(#91): 네이버 소셜 로그인/회원가입 연동 기능 구현2

---

src/main/resources/application.yml

CHORE: 로그 수준 DEBUG로 변경

---

src/main/java/com/fund/stockProject/auth/controller/AuthController.java
src/main/java/com/fund/stockProject/security/filter/JwtAuthenticationFilter.java
src/main/java/com/fund/stockProject/security/principle/CustomUserDetails.java

- close #91
회원 탈퇴 기능 및 JWT 필터 수정, CustomUserDetails 생성

FIX(#91): 회원 탈퇴 기능 및 JWT 필터 수정, CustomUserDetails 생성

---

src/main/java/com/fund/stockProject/auth/controller/AuthController.java
src/main/java/com/fund/stockProject/global/config/SwaggerConfig.java
src/main/resources/application.yml

- close #이슈번호
스웨거 Authorization 버튼 추가

FEAT: 스웨거 Authorization 버튼 추가

---

src/main/java/com/fund/stockProject/auth/controller/OAuth2Controller.java
src/main/java/com/fund/stockProject/auth/dto/GoogleTokenResponse.java
src/main/java/com/fund/stockProject/auth/service/GoogleService.java
src/main/java/com/fund/stockProject/auth/service/OAuth2Service.java
src/main/java/com/fund/stockProject/global/config/SecurityConfig.java
src/main/resources/application.yml

- close #91
구글 소셜 로그인/회원가입 연동 기능 구현

FEAT(#91): 구글 소셜 로그인/회원가입 연동 기능 구현

---

src/main/java/com/fund/stockProject/auth/controller/OAuth2Controller.java
src/main/java/com/fund/stockProject/auth/dto/LoginResponse.java
src/main/java/com/fund/stockProject/auth/service/OAuth2Service.java
src/main/java/com/fund/stockProject/auth/service/TokenService.java

- close #91
로그인 성공 시 이메일, 닉네임 추가로 반환하도록 변경

STYLE(#91): 로그인 성공 시 반환 항목 변경

---

src/main/java/com/fund/stockProject/auth/controller/OAuth2Controller.java
src/main/java/com/fund/stockProject/auth/dto/LoginResponse.java
src/main/java/com/fund/stockProject/auth/service/OAuth2Service.java
src/main/java/com/fund/stockProject/auth/service/TokenService.java

- close #91
로그인 시 state 값 반환하도록 변경

STYLE(#91): 로그인 성공 시 반환 항목 변경2

---

src/main/java/com/fund/stockProject/global/config/SecurityConfig.java
src/main/java/com/fund/stockProject/security/filter/JwtAuthenticationFilter.java
src/main/java/com/fund/stockProject/security/principle/CustomUserDetails.java
src/main/java/com/fund/stockProject/shortview/entity/StockSimilarity.java
src/main/java/com/fund/stockProject/shortview/entity/StockSimilarityId.java
src/main/java/com/fund/stockProject/stock/domain/SECTOR.java
src/main/java/com/fund/stockProject/stock/entity/Stock.java

- close #이슈번호
CustomUserDetails에 User 엔티티 추가
Stock 엔티티에 url, sector, valid 필드 추가

Stock refactor valid

---

src/main/java/com/fund/stockProject/global/controller/ManualBatchController.java
src/main/java/com/fund/stockProject/score/service/ScoreService.java

FIX: score 로직 변경으로 인해 수동 배치 테스트 API 생성

---

src/main/java/com/fund/stockProject/score/repository/ScoreRepository.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

REFACTOR: rising, descent API 성능 개선

---

src/main/java/com/fund/stockProject/score/repository/ScoreRepository.java
src/main/java/com/fund/stockProject/stock/service/StockService.java

Reverts FunD-StockProject/StockProject-Backend#138

Revert "REFACTOR: rising, descent API 성능 개선"

---

src/main/java/com/fund/stockProject/StockProjectApplication.java
src/main/java/com/fund/stockProject/auth/repository/RefreshTokenRepository.java
src/main/java/com/fund/stockProject/auth/service/AuthService.java
src/main/java/com/fund/stockProject/notification/service/StockScoreAlertService.java
src/main/java/com/fund/stockProject/preference/service/PreferenceService.java
src/main/resources/application.yml

FIX: 로그인/회원가입 과정에서의 JDBC 관련 문제 해결

---

src/main/java/com/fund/stockProject/notification/service/FcmPushService.java

REFACTOR: FCM 상세 로그 남게 설정

---

src/main/java/com/fund/stockProject/notification/service/FcmPushService.java

REFACTOR: FCM 상세 로그 남게 설정2

---

src/main/resources/application.yml

CHORE: database source 변경

---

Dockerfile

CHORE: dockerfile 수정2
